# Generated by Django 2.2.3 on 2019-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='manager_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=50),
        ),
    ]
